name: Send Notes

on:
  schedule:
    # Runs every minute
    - cron: '*/1 * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Call the API
      run: curl -X POST https://tlm.aixae.com/api/sendNote
